databases:
  - name: waivolt-postgres-production
    databaseName: waivolt_postgres_production
    user: waivolt

# web server
services:
  - type: web
    name: waivolt-web-production
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: waivolt-postgres-production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  # redis instance
  - type: redis
    name: sidekiq-redis-production
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: []

  # background worker
  - type: worker
    name: sidekiq-worker
    env: ruby
    region: oregon
    buildCommand: "bundle install"
    startCommand: "bundle exec sidekiq -r ./main.rb"
    envVars:
      - key: REDIS_URL
        fromDatabase:
          type: redis
          name: sidekiq-redis-production
          property: connectionString
