shared:
  support: duncan@waivolt.com
  support_mailbox: "Duncan Miller from Waivolt <duncan@waivolt.com>"
  notifications_mailbox: "Waivolt <notifications@waivolt.com>"
  updates_mailbox: "Waivolt <updates@waivolt.com>"
  reminders_mailbox: "Waivolt <reminders@waivolt.com>"
