shared:
  support: duncan@botdevs.ai
  support_mailbox: "Duncan Miller from Waivolt <duncan@botdevs.ai>"
  notifications_mailbox: "Waivolt <notifications@botdevs.ai>"
  updates_mailbox: "Waivolt <updates@botdevs.ai>"
  reminders_mailbox: "Waivolt <reminders@botdevs.ai>"
