shared:
  -
    image: avatar.png
    name: Thomas K.
    testimonial: Right now is a great time for early adopters to get great jobs and for hiring managers to find great talent on Waivolt.
    title: Verified review
    url: https://www.solarbusinessinsights.com/waivolt
  -
    image: avatar.png
    name: Anthony
    testimonial: Stellar customer service.
    title: Technology Sales and Consulting
    url: #
  -
    image: avatar.png
    name: u/Zeus_of_0lympus
    testimonial: This is really cool.
    title: r/solarbusiness
    url: #
