shared:
  -
    image: avatar.png
    name: Anthony
    testimonial: Stellar customer service.
    title: Technology Sales and Consulting
    url: #
  -
    image: avatar.png
    name: u/Zeus_of_0lympus
    testimonial: This is really cool.
    title: r/solarbusiness
    url: #
  # -
  #   image: phil.jpg
  #   name: Phil
  #   testimonial: My lead developer gave notice and I found a replacement in under a week through RailsDevs.
  #   title: Founder, Theatre Digs Booker
  #   url: https://testimonial.to/share/railsdevs-hiring/t/5nDZ3xmVezbr8NvNzy2qpdWj9
